_core:
  default_config_hash: FsPoQBR9MKSFgJCNizl60cAUjLthj3EPn9ii_6rmFws
compact: 1
search: 1
style: dark
support: ''
custom_style: ''
light_logo: ''
dark_logo: ''
light_icon: ''
dark_icon: ''
fixed_elements: 0
